extends Node

signal sonar_entered
signal no_time_left
signal game_won

signal collected_anglerfisch
signal collected_feuerqualle
signal collected_dumbo_oktopus
signal collected_vampirtintenfisch
signal collected_kragenhai
signal collected_blobfisch
signal collected_tiefseekoralle
signal collected_plattenkoralle
signal collected_seestern
signal collected_drachenfisch
signal collected_obj
